#!/usr/bin/env python3
"""LSS Network Tools — PDF Report Generator"""

import sys
import os
import json
from pathlib import Path
from datetime import datetime

try:
    from fpdf import FPDF
except ImportError:
    print("fpdf2 is not installed. Install with: pip3 install fpdf2", file=sys.stderr)
    sys.exit(1)

# ── Colour palette ─────────────────────────────────────────────────────────
C_NAV  = (26,  42,  74)    # dark navy
C_WHT  = (255, 255, 255)   # white
C_LGR  = (245, 245, 245)   # light gray (alt rows)
C_DGR  = (33,  33,  33)    # near-black body text
C_MGR  = (117, 117, 117)   # muted / secondary text
C_SBL  = (232, 240, 254)   # section sub-header bg (light blue)
C_HGH  = (211, 47,  47)    # red   — HIGH
C_WRN  = (245, 124,  0)    # orange — WARNING
C_INF  = (25,  118, 210)   # blue  — INFO
C_ADV  = (56,  142,  60)   # green — ADVICE

SEV_COLORS = {
    "high":    C_HGH,
    "warning": C_WRN,
    "info":    C_INF,
    "advice":  C_ADV,
}


# ── PDF class ──────────────────────────────────────────────────────────────
class Report(FPDF):
    def __init__(self, client, location, date_stamp, logo_path):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.client     = client
        self.location   = location
        self.date_stamp = date_stamp
        self.logo_path  = logo_path
        self._cover_done = False
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 20, 20)

    def header(self):
        if not self._cover_done:
            return
        self.set_fill_color(*C_NAV)
        self.rect(0, 0, 210, 12, "F")
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*C_WHT)
        self.set_xy(8, 3)
        self.cell(
            0, 6,
            f"LSS Network Tools  |  {self.client}  /  {self.location}  |  {self.date_stamp}",
            align="L",
        )
        self.set_text_color(*C_DGR)
        self.set_y(18)

    def footer(self):
        if not self._cover_done:
            return
        self.set_y(-13)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*C_MGR)
        self.cell(
            0, 6,
            f"Page {self.page_no()}  —  Generated by LSS Network Tools",
            align="C",
        )

    # ── Cover page ──────────────────────────────────────────────────────────
    def cover(self):
        # Top navy bar
        self.set_fill_color(*C_NAV)
        self.rect(0, 0, 210, 70, "F")

        # Logo — top-right inside the bar
        if self.logo_path and os.path.exists(self.logo_path):
            try:
                self.image(self.logo_path, x=155, y=8, w=42, h=42)
            except Exception:
                pass

        # Title
        self.set_font("Helvetica", "B", 24)
        self.set_text_color(*C_WHT)
        self.set_xy(20, 18)
        self.cell(125, 12, "Network Audit Report", align="L")
        self.set_font("Helvetica", "", 11)
        self.set_xy(20, 33)
        self.cell(125, 7, "Generated by LSS Network Tools", align="L")

        # Metadata card
        self.set_fill_color(*C_LGR)
        self.set_draw_color(*C_NAV)
        self.rect(20, 82, 170, 56, "FD")
        self.set_text_color(*C_DGR)

        for i, (k, v) in enumerate([
            ("Client",    self.client),
            ("Location",  self.location),
            ("Date",      self.date_stamp),
            ("Generated", datetime.now().strftime("%Y-%m-%d %H:%M")),
        ]):
            y = 89 + i * 11
            self.set_font("Helvetica", "B", 10)
            self.set_xy(28, y)
            self.cell(38, 7, k + ":", align="L")
            self.set_font("Helvetica", "", 10)
            self.cell(0, 7, str(v), align="L")

        self.set_y(155)
        self._cover_done = True

    # ── Layout helpers ──────────────────────────────────────────────────────
    def section_title(self, title):
        self.ln(5)
        self.set_fill_color(*C_NAV)
        self.set_text_color(*C_WHT)
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 8, f"  {title}", fill=True, ln=1)
        self.set_text_color(*C_DGR)
        self.ln(2)

    def subsection_title(self, title):
        self.ln(3)
        self.set_fill_color(*C_SBL)
        self.set_text_color(*C_NAV)
        self.set_font("Helvetica", "B", 9)
        self.cell(0, 7, f"  {title}", fill=True, ln=1)
        self.set_text_color(*C_DGR)
        self.ln(1)

    def kv(self, key, value, shade=False):
        if shade:
            self.set_fill_color(*C_LGR)
        self.set_font("Helvetica", "B", 8)
        fill = shade
        self.cell(52, 5, f"  {key}", fill=fill)
        self.set_font("Helvetica", "", 8)
        text = str(value) if value is not None else "\u2014"
        self.multi_cell(0, 5, text, fill=fill)

    def finding_row(self, severity, title, detail, shade=False):
        color = SEV_COLORS.get(severity.lower(), C_MGR)
        if shade:
            self.set_fill_color(*C_LGR)
            self.rect(self.l_margin, self.get_y(), 170, 5, "F")
        # Severity badge
        self.set_fill_color(*color)
        self.set_text_color(*C_WHT)
        self.set_font("Helvetica", "B", 7)
        self.cell(22, 5, severity.upper(), fill=True, align="C")
        # Title on same line
        self.set_text_color(*C_DGR)
        self.set_font("Helvetica", "B", 8)
        self.cell(0, 5, f"  {title}", ln=1)
        # Detail indented
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*C_MGR)
        self.set_x(self.l_margin + 24)
        self.multi_cell(146, 4, detail)
        self.set_text_color(*C_DGR)
        self.ln(1)

    def hint_row(self, title, detail, shade=False):
        if shade:
            self.set_fill_color(*C_LGR)
        self.set_font("Helvetica", "B", 8)
        self.cell(0, 5, f"  {title}", fill=shade, ln=1)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*C_MGR)
        self.set_x(self.l_margin + 4)
        self.multi_cell(166, 4, detail)
        self.set_text_color(*C_DGR)
        self.ln(1)

    def note(self, text):
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*C_MGR)
        self.cell(0, 5, f"  {text}", ln=1)
        self.set_text_color(*C_DGR)


# ── Data helpers ──────────────────────────────────────────────────────────
def load_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def task_json_path(run_dir, manifest, task_id):
    """Return Path to the primary JSON for a given task_id, or None."""
    for t in manifest.get("tasks", []):
        try:
            if int(t.get("task_id", -1)) == task_id:
                files = t.get("json_files") or []
                if files:
                    return run_dir / files[0]
                jf = t.get("json_file")
                if jf:
                    return run_dir / jf
        except (TypeError, ValueError):
            continue
    return None


def all_task_json_paths(run_dir, manifest, task_id):
    """Return list of existing Paths for all JSON files of a multi-entry task."""
    for t in manifest.get("tasks", []):
        try:
            if int(t.get("task_id", -1)) == task_id:
                return [
                    run_dir / f
                    for f in (t.get("json_files") or [])
                    if (run_dir / f).exists()
                ]
        except (TypeError, ValueError):
            continue
    return []


# ── Task renderers ────────────────────────────────────────────────────────
def render_interface_info(pdf, data):
    pdf.subsection_title("1. Interface Network Info")
    for i, (k, v) in enumerate([
        ("Interface",    data.get("interface")),
        ("IP Address",   data.get("ip_address")),
        ("Subnet Mask",  data.get("subnet")),
        ("Network Range",data.get("network")),
        ("Gateway",      data.get("gateway")),
        ("MAC Address",  data.get("mac_address")),
    ]):
        pdf.kv(k, v or "unknown", shade=i % 2 == 0)


def render_speed_test(pdf, data):
    pdf.subsection_title("2. Internet Speed Test")
    ping  = data.get("ping_ms")
    dl    = data.get("download_mbps")
    ul    = data.get("upload_mbps")
    for i, (k, v) in enumerate([
        ("Public IP",   data.get("public_ip")),
        ("Test Server", data.get("server_name")),
        ("Ping",        f"{ping} ms"   if ping is not None else "unknown"),
        ("Download",    f"{dl} Mbps"   if dl   is not None else "unknown"),
        ("Upload",      f"{ul} Mbps"   if ul   is not None else "unknown"),
    ]):
        pdf.kv(k, v or "unknown", shade=i % 2 == 0)


def render_gateway(pdf, data):
    pdf.subsection_title("3. Gateway Details")
    ports = data.get("open_ports") or []
    pdf.kv("Gateway IP",      data.get("gateway_ip", "unknown"), shade=False)
    pdf.kv("Open Port Count", str(len(ports)),                   shade=True)
    pdf.kv("Open TCP Ports",  ", ".join(str(p) for p in ports) or "none", shade=False)


def render_dhcp(pdf, data):
    pdf.subsection_title("4. DHCP Network Scan")
    for i, (k, v) in enumerate([
        ("Discovery Attempts",  data.get("discovery_attempts")),
        ("Responders Observed", data.get("dhcp_responders_observed", 0)),
        ("Offers Observed",     data.get("offers_observed", 0)),
        ("Rogue DHCP Suspected",data.get("rogue_dhcp_suspected", False)),
    ]):
        pdf.kv(k, v, shade=i % 2 == 0)
    for ip in data.get("suspected_rogue_servers") or []:
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*C_HGH)
        pdf.cell(0, 5, f"  ! Suspected rogue responder: {ip}", ln=1)
        pdf.set_text_color(*C_DGR)


def render_generic_scan(pdf, num, title, data):
    pdf.subsection_title(f"{num}. {title}")
    servers = data.get("servers") or []
    if not servers:
        pdf.note("No hosts detected.")
        return
    for srv in servers:
        ip       = srv.get("ip", "unknown")
        ports    = ", ".join(str(p) for p in (srv.get("open_ports") or [])) or "none"
        services = ", ".join(srv.get("detected_services") or []) or "unknown"
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*C_DGR)
        pdf.cell(0, 5, f"  {ip}", ln=1)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*C_MGR)
        pdf.cell(0, 4, f"    Ports: {ports}   |   Services: {services}", ln=1)
    pdf.set_text_color(*C_DGR)


def render_stress_test(pdf, num, label, data):
    pdf.subsection_title(f"{num}. {label}")
    target = data.get("target_ip") or data.get("gateway_ip", "unknown")
    ind    = data.get("indicators") or {}
    for i, (k, v) in enumerate([
        ("Target",             target),
        ("High Jitter",        ind.get("high_jitter",        False)),
        ("Latency Under Load", ind.get("latency_under_load", False)),
        ("Packet Loss",        ind.get("packet_loss",        False)),
        ("Slow Recovery",      ind.get("slow_recovery",      False)),
    ]):
        pdf.kv(k, v, shade=i % 2 == 0)
    stages = data.get("stages") or []
    if stages:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, "  Stage Results:", ln=1)
        for s in stages:
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*C_MGR)
            pdf.cell(
                0, 4,
                f"    {s.get('stage','?')}:  avg {s.get('avg_ms','?')} ms  |  loss {s.get('packet_loss_pct','?')}%",
                ln=1,
            )
        pdf.set_text_color(*C_DGR)


def render_vlan_trunk(pdf, data):
    pdf.subsection_title("12. VLAN / Trunk Detection")
    vlan_ids = data.get("observed_vlan_ids") or []
    ind      = data.get("indicators") or {}
    for i, (k, v) in enumerate([
        ("Interface",            data.get("interface")),
        ("Tagged Frames Observed",data.get("tagged_frames_observed", False)),
        ("Observed VLAN IDs",    ", ".join(str(v) for v in vlan_ids) or "none"),
        ("Trunk Port Suspected", ind.get("trunk_port_suspected", False)),
        ("CDP/LLDP Exposure",    ind.get("cdp_exposed",          False)),
        ("Multiple VLANs Visible",ind.get("multiple_vlans_visible", False)),
    ]):
        pdf.kv(k, v, shade=i % 2 == 0)

    cdp  = data.get("cdp_neighbours")  or []
    lldp = data.get("lldp_neighbours") or []

    if cdp:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, f"  CDP Neighbours ({len(cdp)}):", ln=1)
        for n in cdp:
            vlan = str(n.get("native_vlan")) if n.get("native_vlan") is not None else "unknown"
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*C_MGR)
            pdf.cell(
                0, 4,
                f"    {n.get('device_id','?')}  |  {n.get('platform','?')}"
                f"  |  Port: {n.get('port_id','?')}  |  Native VLAN: {vlan}"
                f"  |  Duplex: {n.get('duplex','?')}",
                ln=1,
            )
        pdf.set_text_color(*C_DGR)

    if lldp:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, f"  LLDP Neighbours ({len(lldp)}):", ln=1)
        for n in lldp:
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*C_MGR)
            pdf.cell(
                0, 4,
                f"    {n.get('system_name','?')}  |  Chassis: {n.get('chassis_id','?')}"
                f"  |  Port: {n.get('port_id','?')}",
                ln=1,
            )
        pdf.set_text_color(*C_DGR)


def render_custom_port_scan(pdf, data, index):
    target = data.get("target_ip", "unknown")
    pdf.subsection_title(f"10. Custom Target Port Scan — {target}  (device {index})")
    ports = data.get("open_ports") or []
    pdf.kv("Target IP",       target,                                            shade=False)
    pdf.kv("Open Port Count", str(len(ports)),                                   shade=True)
    pdf.kv("Open TCP Ports",  ", ".join(str(p) for p in ports) or "none",        shade=False)


def render_custom_stress(pdf, data, index):
    target = data.get("target_ip", "unknown")
    render_stress_test(pdf, 11, f"Custom Target Stress Test — {target}  (device {index})", data)


def render_custom_identity(pdf, data, index):
    target = data.get("target_ip", "unknown")
    pdf.subsection_title(f"13. Custom Target Identity Scan — {target}  (device {index})")
    for i, (k, v) in enumerate([
        ("Target IP",       target),
        ("Hostname",        data.get("hostname")),
        ("MAC Address",     data.get("mac_address")),
        ("Vendor",          data.get("vendor")),
        ("Device Type Hint",data.get("device_type_hint")),
        ("Confidence",      data.get("confidence")),
        ("Identity Summary",data.get("identity_summary")),
    ]):
        pdf.kv(k, v, shade=i % 2 == 0)


def render_custom_dns_assessment(pdf, data, index):
    target = data.get("target_ip", "unknown")
    pdf.subsection_title(f"14. Custom DNS Assessment — {target}  (device {index})")
    for i, (k, v) in enumerate([
        ("Target IP",          target),
        ("DNS Service Working", data.get("dns_service_working", False)),
        ("Recursion Available", data.get("recursion_available", False)),
        ("UDP Query Status",    (data.get("udp_query") or {}).get("status")),
        ("TCP Query Status",    (data.get("tcp_query") or {}).get("status")),
        ("Software Hint",       data.get("software_hint")),
    ]):
        pdf.kv(k, v, shade=i % 2 == 0)


# ── Main ──────────────────────────────────────────────────────────────────
def main():
    if len(sys.argv) < 3:
        print("Usage: generate_pdf_report.py <run_output_dir> <app_root>", file=sys.stderr)
        sys.exit(1)

    run_dir  = Path(sys.argv[1])
    app_root = Path(sys.argv[2])
    logo     = app_root / "assets" / "logo.svg"

    manifest        = load_json(run_dir / "manifest.json")        or {}
    findings_data   = load_json(run_dir / "findings.json")        or {}
    remediation_data= load_json(run_dir / "remediation.json")     or {}

    client     = manifest.get("client",       "Unknown Client")
    location   = manifest.get("location",     "Unknown Location")
    date_stamp = manifest.get("generated_at", "Unknown Date")

    pdf = Report(
        client     = client,
        location   = location,
        date_stamp = date_stamp,
        logo_path  = str(logo) if logo.exists() else None,
    )
    pdf.add_page()
    pdf.cover()

    # ── Executive Summary ──────────────────────────────────────────────────
    pdf.section_title("Executive Summary \u2014 Key Findings")
    findings = findings_data.get("findings") or []
    if not findings:
        pdf.note("No notable findings were generated from this scan set.")
    else:
        for i, f in enumerate(findings):
            pdf.finding_row(
                f.get("severity", "info"),
                f.get("title",    ""),
                f.get("detail",   ""),
                shade=i % 2 == 0,
            )

    # ── Remediation Hints ──────────────────────────────────────────────────
    hints = remediation_data.get("hints") or []
    if hints:
        pdf.section_title("Remediation Hints")
        for i, h in enumerate(hints):
            pdf.hint_row(h.get("title", ""), h.get("detail", ""), shade=i % 2 == 0)

    # ── Audit Results ──────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Audit Results")

    def get(task_id):
        p = task_json_path(run_dir, manifest, task_id)
        return load_json(p) if p and p.exists() else None

    if d := get(1):  render_interface_info(pdf, d)
    if d := get(2):  render_speed_test(pdf, d)
    if d := get(3):  render_gateway(pdf, d)
    if d := get(4):  render_dhcp(pdf, d)
    if d := get(5):  render_generic_scan(pdf, 5,  "DNS Network Scan",              d)
    if d := get(6):  render_generic_scan(pdf, 6,  "LDAP/AD Network Scan",          d)
    if d := get(7):  render_generic_scan(pdf, 7,  "SMB/NFS Network Scan",          d)
    if d := get(8):  render_generic_scan(pdf, 8,  "Printer/Print Server Scan",     d)
    if d := get(9):  render_stress_test(pdf, 9,   "Gateway Stress Test",           d)
    if d := get(12): render_vlan_trunk(pdf, d)

    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 10), 1):
        if d := load_json(p): render_custom_port_scan(pdf, d, i)
    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 11), 1):
        if d := load_json(p): render_custom_stress(pdf, d, i)
    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 13), 1):
        if d := load_json(p): render_custom_identity(pdf, d, i)
    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 14), 1):
        if d := load_json(p): render_custom_dns_assessment(pdf, d, i)

    # ── Output path ────────────────────────────────────────────────────────
    report_txt = manifest.get("report_file", "")
    if report_txt:
        pdf_path = run_dir / (Path(report_txt).stem + ".pdf")
    else:
        def slug(s): return s.lower().replace(" ", "-")
        pdf_path = run_dir / f"lss-network-tools-report-{slug(client)}-{slug(location)}.pdf"

    pdf.output(str(pdf_path))
    print(str(pdf_path))


if __name__ == "__main__":
    main()
