#!/usr/bin/env python3
"""LSS Network Tools -- PDF Report Generator"""

import sys
import os
import json
from pathlib import Path

try:
    from fpdf import FPDF
except ImportError:
    print("fpdf2 is not installed. Install with: pip3 install fpdf2", file=sys.stderr)
    sys.exit(1)

# ── Colour palette ─────────────────────────────────────────────────────────
C_NAV  = (26,  42,  74)    # dark navy
C_WHT  = (255, 255, 255)   # white
C_LGR  = (245, 245, 245)   # light gray (alt rows)
C_DGR  = (33,  33,  33)    # near-black body text
C_MGR  = (117, 117, 117)   # muted / secondary text
C_SBL  = (232, 240, 254)   # section sub-header bg (light blue)
C_HGH  = (211, 47,  47)    # red   -- HIGH
C_WRN  = (245, 124,  0)    # orange -- WARNING
C_INF  = (25,  118, 210)   # blue  -- INFO
C_ADV  = (56,  142,  60)   # green -- ADVICE

SEV_COLORS = {
    "high":    C_HGH,
    "warning": C_WRN,
    "info":    C_INF,
    "advice":  C_ADV,
}


# ── PDF class ──────────────────────────────────────────────────────────────
class Report(FPDF):
    def __init__(self, client, location, note, date_stamp, prepared_by, logo_path):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.client      = client
        self.location    = location
        self.run_note    = note
        self.date_stamp  = date_stamp
        self.prepared_by = prepared_by
        self.logo_path   = logo_path
        self._cover_done = False
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 20, 20)
        self.alias_nb_pages()

    def header(self):
        if not self._cover_done:
            return
        self.set_fill_color(*C_NAV)
        self.rect(0, 0, 210, 12, "F")
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*C_WHT)
        self.set_xy(8, 3)
        self.cell(
            0, 6,
            safe(f"LSS Network Tools  |  {self.client}  /  {self.location}  |  {self.date_stamp}"),
            align="L",
        )
        self.set_text_color(*C_DGR)
        self.set_y(18)

    def footer(self):
        if not self._cover_done:
            return
        self.set_y(-13)
        self.set_font("Helvetica", "I", 7)
        # Cover page has a navy strip at the bottom — use white so the text is readable
        self.set_text_color(*C_WHT if self.page_no() == 1 else C_MGR)
        self.cell(
            0, 6,
            safe(f"Page {self.page_no()} of {{nb}}  --  Generated by LSS Network Tools (LS Solutions Software)"),
            align="C",
        )

    # ── Cover page ──────────────────────────────────────────────────────────
    def cover(self):
        self.set_auto_page_break(False)   # prevent any cover element triggering a new page

        C_ACC  = (74, 144, 226)   # light blue accent
        C_DIM  = (160, 190, 230)  # dimmed white for subtitle
        C_NVL  = (38,  60, 100)   # slightly lighter navy for node fills
        NAVY_H = 162              # mm — navy band height (~55% of A4)

        # ── Full-width navy band ──────────────────────────────────────────
        self.set_fill_color(*C_NAV)
        self.rect(0, 0, 210, NAVY_H, "F")

        # ── Decorative network topology (lower-right of navy band) ───────
        nodes = [
            (136, 108), (154,  97), (174, 112), (170, 132),
            (150, 143), (188, 101), (128, 136), (192, 124),
        ]
        edges = [(0,1),(1,2),(2,5),(2,3),(3,4),(0,4),(1,4),(5,7),(2,7),(3,7),(6,0),(6,4)]
        self.set_draw_color(*C_ACC)
        self.set_line_width(0.35)
        for a, b in edges:
            ax, ay = nodes[a]; bx, by = nodes[b]
            self.line(ax, ay, bx, by)
        # Node circles — outer ring in accent, filled with lighter navy
        for nx, ny in nodes:
            self.set_fill_color(*C_NVL)
            self.ellipse(nx - 2.8, ny - 2.8, 5.6, 5.6, "FD")
        # Centre dot in accent colour
        self.set_fill_color(*C_ACC)
        for nx, ny in nodes:
            self.ellipse(nx - 1.2, ny - 1.2, 2.4, 2.4, "F")

        # Horizontal accent line separating logo from title
        DIV_Y = 72
        self.set_draw_color(*C_ACC)
        self.set_line_width(1.0)
        self.line(20, DIV_Y, 190, DIV_Y)

        # ── Logo (centered above divider) ────────────────────────────────
        logo_rendered = False
        if self.logo_path and os.path.exists(self.logo_path):
            try:
                lw = 44
                lh = lw * (810 / 912)          # preserve aspect ratio
                self.image(self.logo_path, x=(210 - lw) / 2, y=15, w=lw, h=lh)
                logo_rendered = True
            except Exception:
                pass
        if not logo_rendered:
            self.set_font("Helvetica", "B", 30)
            self.set_text_color(*C_WHT)
            self.set_xy(0, 25)
            self.cell(210, 16, "LSS", align="C")

        # ── Report title ─────────────────────────────────────────────────
        self.set_font("Helvetica", "B", 26)
        self.set_text_color(*C_WHT)
        self.set_xy(0, DIV_Y + 7)
        self.cell(210, 13, "NETWORK AUDIT REPORT", align="C")

        # ── Subtitle ─────────────────────────────────────────────────────
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*C_DIM)
        self.set_xy(0, DIV_Y + 22)
        self.cell(210, 6, safe("LS Solutions Software  \u2014  LSS Network Tools"), align="C")

        # ── Metadata card (white area below navy band) ───────────────────
        rows = [("Client", self.client), ("Location", self.location)]
        if self.run_note:
            rows.append(("Note", self.run_note))
        rows.append(("Date", self.date_stamp))
        if self.prepared_by:
            rows.append(("Prepared By", self.prepared_by))

        CARD_W    = 84                       # ~50% of original 166 mm
        CARD_L    = (210 - CARD_W) // 2     # centred on A4 (63 mm)
        CARD_TOP  = NAVY_H + 4
        LABEL_W   = 30          # uppercase label column
        VAL_W     = CARD_W - LABEL_W - 18   # value column (36 mm)
        LINE_H    = 5.5
        ROW_PAD   = 1           # top + bottom padding inside each row
        ROW_H     = LINE_H + ROW_PAD * 2   # 7.5 mm per single-line row

        # Pre-measure row heights (values may wrap)
        self.set_font("Helvetica", "", 8)
        row_heights = []
        for k, v in rows:
            val_str = safe(str(v or ""))
            words   = val_str.split()
            n, lw   = 1, 0.0
            for word in words:
                ww = self.get_string_width(word + " ")
                if lw + ww > VAL_W - 2:
                    n += 1; lw = ww
                else:
                    lw += ww
            row_heights.append(max(ROW_H, n * LINE_H + ROW_PAD * 2))

        CARD_H = sum(row_heights) + ROW_PAD * 2

        # Card shadow
        self.set_fill_color(210, 215, 225)
        self.rect(CARD_L + 2, CARD_TOP + 2, CARD_W, CARD_H, "F")

        # Card background — clean white with navy border
        self.set_fill_color(255, 255, 255)
        self.set_draw_color(*C_NAV)
        self.set_line_width(0.4)
        self.rect(CARD_L, CARD_TOP, CARD_W, CARD_H, "FD")

        # Left navy accent bar
        self.set_fill_color(*C_NAV)
        self.rect(CARD_L, CARD_TOP, 5, CARD_H, "F")

        y = CARD_TOP + ROW_PAD
        for i, ((k, v), row_h) in enumerate(zip(rows, row_heights)):
            # Navy separator between rows (not before first)
            if i > 0:
                self.set_draw_color(*C_NAV)
                self.set_line_width(0.3)
                self.line(CARD_L + 5, y, CARD_L + CARD_W, y)

            mid_y = y + (row_h - LINE_H) / 2

            # Label in navy
            self.set_font("Helvetica", "B", 8)
            self.set_text_color(*C_NAV)
            self.set_xy(CARD_L + 8, mid_y)
            self.cell(LABEL_W, LINE_H, safe(k.upper() + ":"), align="L")

            # Value in dark navy
            self.set_font("Helvetica", "", 8)
            self.set_text_color(*C_NAV)
            self.set_xy(CARD_L + 8 + LABEL_W, y + ROW_PAD)
            self.multi_cell(VAL_W, LINE_H, safe(str(v or "")), align="L",
                            new_x="LMARGIN", new_y="NEXT")
            y += row_h

        # ── Confidentiality note (above strip) ───────────────────────────
        self.set_font("Helvetica", "I", 7.5)
        self.set_text_color(*C_MGR)
        self.set_xy(20, 258)
        self.cell(170, 5,
            "This document is confidential and intended solely for the use of the named client.",
            align="C")

        # ── Confidentiality strip (bottom of page) ───────────────────────
        self.set_fill_color(*C_NAV)
        self.rect(0, 268, 210, 29, "F")
        # Top accent line on strip
        self.set_draw_color(*C_ACC)
        self.set_line_width(0.8)
        self.line(0, 268, 210, 268)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*C_WHT)
        self.set_xy(0, 275)
        self.cell(210, 5, safe(f"CONFIDENTIAL  \u2014  Prepared for {self.client}"), align="C")
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*C_DIM)
        self.set_xy(0, 282)
        self.cell(210, 5, "Not for distribution beyond the named recipient", align="C")

        self.set_auto_page_break(True, margin=20)
        self._cover_done = True

    # ── Layout helpers ──────────────────────────────────────────────────────
    def section_title(self, title):
        self.ln(5)
        self.set_fill_color(*C_NAV)
        self.set_text_color(*C_WHT)
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 8, safe(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)
        self.ln(2)

    def subsection_title(self, title):
        self.ln(3)
        self.set_fill_color(*C_SBL)
        self.set_text_color(*C_NAV)
        self.set_font("Helvetica", "B", 9)
        self.cell(0, 7, safe(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)
        self.ln(1)

    def kv(self, key, value, shade=False):
        self.set_x(self.l_margin)
        if shade:
            self.set_fill_color(*C_LGR)
        self.set_font("Helvetica", "B", 8)
        self.cell(52, 5, safe(f"  {key}"), fill=shade)
        self.set_font("Helvetica", "", 8)
        val_w = self.w - self.l_margin - self.r_margin - 52
        self.multi_cell(val_w, 5, safe(str(value) if value is not None else "--"), fill=shade,
                        new_x="LMARGIN", new_y="NEXT")

    def finding_row(self, severity, title, detail, shade=False):
        color = SEV_COLORS.get(severity.lower(), C_MGR)
        if shade:
            self.set_fill_color(*C_LGR)
            self.rect(self.l_margin, self.get_y(), 170, 5, "F")
        # Severity badge
        self.set_fill_color(*color)
        self.set_text_color(*C_WHT)
        self.set_font("Helvetica", "B", 7)
        self.cell(22, 5, safe(severity.upper()), fill=True, align="C")
        # Title on same line
        self.set_text_color(*C_DGR)
        self.set_font("Helvetica", "B", 8)
        self.cell(148, 5, safe(f"  {title}"), new_x="LMARGIN", new_y="NEXT")
        # Detail indented
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*C_MGR)
        self.set_x(self.l_margin + 24)
        self.multi_cell(146, 4, safe(detail), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)
        self.ln(1)

    def hint_row(self, title, detail, shade=False):
        if shade:
            self.set_fill_color(*C_LGR)
            self.set_font("Helvetica", "B", 8)
            self.cell(170, 5, safe(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        else:
            # Accent bar on the left for unshaded rows
            bar_y = self.get_y()
            self.set_font("Helvetica", "B", 8)
            self.cell(170, 5, safe(f"  {title}"), fill=False, new_x="LMARGIN", new_y="NEXT")
            self.set_draw_color(*C_NAV)
            self.set_line_width(0.6)
            self.line(self.l_margin, bar_y, self.l_margin, bar_y + 5)
            self.set_line_width(0.2)
        self.set_font("Helvetica", "B", 8)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*C_MGR)
        self.set_x(self.l_margin + 4)
        self.multi_cell(166, 4, safe(detail), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)
        self.ln(1)

    def kv_flag(self, key, value, shade=False):
        """Like kv() but renders boolean True/False with colour (red/green)."""
        self.set_x(self.l_margin)
        if shade:
            self.set_fill_color(*C_LGR)
        self.set_font("Helvetica", "B", 8)
        self.cell(52, 5, safe(f"  {key}"), fill=shade)
        bool_val = value is True or str(value).lower() == "true"
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*(C_HGH if bool_val else C_ADV))
        val_w = self.w - self.l_margin - self.r_margin - 52
        self.multi_cell(val_w, 5, "Yes" if bool_val else "No",
                        fill=shade, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)

    def note(self, text):
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*C_MGR)
        self.multi_cell(0, 4.5, safe(f"  {text}"), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)


# ── Text helpers ──────────────────────────────────────────────────────────
def safe(text):
    """Transliterate common unicode chars then strip anything still outside latin-1."""
    if text is None:
        return "--"
    s = str(text)
    s = s.replace("\u2014", "--").replace("\u2013", "-")   # em/en dash
    s = s.replace("\u2019", "'").replace("\u2018", "'")    # curly single quotes
    s = s.replace("\u201c", '"').replace("\u201d", '"')    # curly double quotes
    s = s.replace("\u03c3", "stddev").replace("\u00b0", "deg")  # sigma, degree
    s = s.replace("\u2022", "*").replace("\u00a9", "(c)")  # bullet, copyright
    return s.encode("latin-1", errors="replace").decode("latin-1")


# ── Data helpers ──────────────────────────────────────────────────────────
def load_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def task_json_path(run_dir, manifest, task_id):
    """Return Path to the primary JSON for a given task_id, or None."""
    for t in manifest.get("tasks", []):
        try:
            if int(t.get("task_id", -1)) == task_id:
                files = t.get("json_files") or []
                if files:
                    return run_dir / files[0]
                jf = t.get("json_file")
                if jf:
                    return run_dir / jf
        except (TypeError, ValueError):
            continue
    return None


def all_task_json_paths(run_dir, manifest, task_id):
    """Return list of existing Paths for all JSON files of a multi-entry task."""
    for t in manifest.get("tasks", []):
        try:
            if int(t.get("task_id", -1)) == task_id:
                return [
                    run_dir / f
                    for f in (t.get("json_files") or [])
                    if (run_dir / f).exists()
                ]
        except (TypeError, ValueError):
            continue
    return []


# ── Task renderers ────────────────────────────────────────────────────────
def render_interface_info(pdf, data):
    pdf.subsection_title("1. Interface Network Info")
    for i, (k, v) in enumerate([
        ("Interface",    data.get("interface")),
        ("IP Address",   data.get("ip_address")),
        ("Subnet Mask",  data.get("subnet")),
        ("Network Range",data.get("network")),
        ("Gateway",      data.get("gateway")),
        ("MAC Address",  data.get("mac_address")),
    ]):
        pdf.kv(k, v or "unknown", shade=i % 2 == 0)
    if data.get("is_vm"):
        vm_plat = data.get("vm_platform") or "unknown hypervisor"
        pdf.note(f"Running inside a virtual machine ({vm_plat}). Results reflect the virtualised network stack; physical-layer findings (e.g. Wi-Fi, VLAN tagging) may not be observable from within a VM.")


def render_speed_test(pdf, data):
    pdf.subsection_title("2. Internet Speed Test")
    srv   = (data.get("servers") or [{}])[0]
    ping  = srv.get("ping_ms")
    dl    = srv.get("download_mbps")
    ul    = srv.get("upload_mbps")
    for i, (k, v) in enumerate([
        ("Public IP",   srv.get("public_ip") or data.get("public_ip")),
        ("Test Server", srv.get("test_server") or srv.get("server_name")),
        ("Ping",        f"{ping} ms"   if ping is not None else "unknown"),
        ("Download",    f"{dl} Mbps"   if dl   is not None else "unknown"),
        ("Upload",      f"{ul} Mbps"   if ul   is not None else "unknown"),
    ]):
        pdf.kv(k, v or "unknown", shade=i % 2 == 0)
    if m := data.get("methodology"):
        pdf.note(m)


def render_gateway(pdf, data):
    pdf.subsection_title("3. Gateway Details")
    ports = data.get("open_ports") or []
    pdf.kv("Gateway IP",      data.get("gateway_ip", "unknown"), shade=False)
    pdf.kv("Open Port Count", str(len(ports)),                   shade=True)
    pdf.kv("Open TCP Ports",  ", ".join(str(p) for p in ports) or "none", shade=False)
    if scope := data.get("scan_scope"):
        pdf.note(f"Scan scope: {scope}")


def render_dhcp(pdf, data):
    pdf.subsection_title("4. DHCP Network Scan")
    relay_raw = data.get("relay_sources_seen") or []
    relay = ", ".join(relay_raw) or "none"
    pdf.kv("Discovery Attempts",   data.get("discovery_attempts"),        shade=True)
    pdf.kv("Responders Observed",  data.get("dhcp_responders_observed", 0), shade=False)
    pdf.kv("Unique Offers",        data.get("offers_observed", 0),          shade=True)
    pdf.kv("Raw Offers Captured",  data.get("raw_offers_observed", 0),      shade=False)
    pdf.kv_flag("Rogue DHCP Suspected", data.get("rogue_dhcp_suspected", False), shade=True)
    pdf.kv("Relay / Proxy Sources", relay,                                  shade=False)
    responder_ips = {srv.get("ip") for srv in (data.get("servers") or [])}
    relay_only = [ip for ip in relay_raw if ip not in responder_ips]
    if relay_only:
        pdf.note(f"Relay/proxy only (no DHCP offers issued): {', '.join(relay_only)}")
    for ip in data.get("suspected_rogue_servers") or []:
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*C_HGH)
        pdf.cell(0, 5, safe(f"  ! Suspected rogue responder: {ip}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*C_DGR)
    servers = data.get("servers") or []
    if servers:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, safe(f"  DHCP Responders ({len(servers)}):"), new_x="LMARGIN", new_y="NEXT")
        for srv in servers:
            ports = ", ".join(str(p) for p in (srv.get("open_ports") or [])) or "none"
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*C_MGR)
            pdf.set_x(pdf.l_margin + 4)
            pdf.multi_cell(
                166, 4,
                safe(f"{srv.get('ip','?')}  |  Class: {srv.get('classification','unknown')}"
                     f"  |  Offers: {srv.get('offers_observed',0)}"
                     f"  |  Rogue: {srv.get('suspected_rogue', False)}"
                     f"  |  Ports: {ports}"),
                new_x="LMARGIN", new_y="NEXT",
            )
        pdf.set_text_color(*C_DGR)


def render_dhcp_response_time(pdf, data):
    pdf.subsection_title("5. DHCP Response Time")
    iface    = data.get("interface")         or "unknown"
    server   = data.get("server_ip")         or "unknown"
    probes   = data.get("probe_count",        0)
    responded= data.get("responded_count",    0)
    loss     = data.get("packet_loss_percent",0)
    avg_ms   = data.get("avg_ms")
    min_ms   = data.get("min_ms")
    max_ms   = data.get("max_ms")
    ind      = data.get("indicators")        or {}
    is_wifi  = data.get("is_wifi",            False)

    iface_label = f"{iface}  (Wi-Fi)" if is_wifi else iface
    pdf.kv("Interface",       iface_label,                                             shade=False)
    pdf.kv("DHCP Server",     server,                                                  shade=True)
    pdf.kv("Probes / Replies",f"{probes} / {responded}",                              shade=False)
    pdf.kv("Packet Loss",     f"{loss}%",                                              shade=True)
    pdf.kv("Min Latency",     f"{min_ms} ms" if min_ms is not None else "N/A",        shade=False)
    pdf.kv("Avg Latency",     f"{avg_ms} ms" if avg_ms is not None else "N/A",        shade=True)
    pdf.kv("Max Latency",     f"{max_ms} ms" if max_ms is not None else "N/A",        shade=False)
    pdf.kv_flag("Slow Response", ind.get("slow_response", False),                     shade=True)
    pdf.kv_flag("Packet Loss",   ind.get("high_loss",     False),                     shade=False)

    if is_wifi:
        pdf.note("Measured over Wi-Fi — wireless adds inherent latency. Re-test on a wired connection for a reliable baseline.")
    if m := data.get("methodology"):
        pdf.note(m)

    times = data.get("response_times_ms") or []
    if times:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*C_DGR)
        pdf.cell(0, 5, safe("  Per-Probe Results:"), new_x="LMARGIN", new_y="NEXT")
        for i, t in enumerate(times):
            val = f"{t} ms" if t is not None else "no response"
            col = C_HGH if t is None else C_DGR
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*col)
            pdf.cell(0, 4, safe(f"    Probe {i+1}: {val}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*C_DGR)


def render_smb_nfs(pdf, data):
    pdf.subsection_title("8. SMB/NFS Network Scan")
    network    = data.get("network") or "unknown"
    scan_ports = data.get("scan_ports") or "unknown"
    servers    = data.get("servers") or []
    pdf.kv("Network Range",  network,    shade=False)
    pdf.kv("Scanned Ports",  scan_ports, shade=True)
    pdf.kv("Servers Found",  len(servers), shade=False)
    if not servers:
        pdf.note("No hosts detected.")
        return
    pdf.ln(1)
    for srv in servers:
        ip       = srv.get("ip", "unknown")
        ports    = ", ".join(str(p) for p in (srv.get("open_ports") or [])) or "none"
        services = ", ".join(srv.get("detected_services") or []) or "unknown"
        signing  = srv.get("smb_signing_required")
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*C_DGR)
        pdf.cell(0, 5, safe(f"  {ip}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*C_MGR)
        pdf.multi_cell(0, 4, safe(f"    Ports: {ports}   |   Services: {services}"), new_x="LMARGIN", new_y="NEXT")
        if signing is not None:
            if signing:
                sign_label = "Required (secure)"
                pdf.set_text_color(*C_ADV)
            else:
                sign_label = "Not required (vulnerable to relay attacks)"
                pdf.set_text_color(*C_HGH)
            pdf.multi_cell(0, 4, safe(f"    SMB Signing: {sign_label}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*C_DGR)


def render_generic_scan(pdf, num, title, data):
    pdf.subsection_title(f"{num}. {title}")
    network    = data.get("network") or "unknown"
    scan_ports = data.get("scan_ports") or "unknown"
    servers    = data.get("servers") or []
    pdf.kv("Network Range",  network,    shade=False)
    pdf.kv("Scanned Ports",  scan_ports, shade=True)
    pdf.kv("Servers Found",  len(servers), shade=False)
    if not servers:
        pdf.note("No hosts detected.")
        return
    pdf.ln(1)
    for srv in servers:
        ip       = srv.get("ip", "unknown")
        ports    = ", ".join(str(p) for p in (srv.get("open_ports") or [])) or "none"
        services = ", ".join(srv.get("detected_services") or []) or "unknown"
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*C_DGR)
        pdf.cell(0, 5, safe(f"  {ip}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*C_MGR)
        pdf.multi_cell(0, 4, safe(f"    Ports: {ports}   |   Services: {services}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*C_DGR)


def render_stress_test(pdf, num, label, data):
    pdf.subsection_title(f"{num}. {label}")
    target     = data.get("gateway") or data.get("target_ip") or data.get("gateway_ip", "unknown")
    ind        = data.get("indicators") or {}
    ss         = data.get("stage_status") or {}
    baseline   = data.get("baseline")         or {}
    jitter     = data.get("jitter_test")      or {}
    large      = data.get("large_packet_test") or {}
    sustained  = data.get("sustained_test")   or {}
    recovery   = data.get("recovery")         or {}

    base_avg = baseline.get("avg_latency_ms")
    sust_avg = sustained.get("avg_latency_ms")

    pdf.kv("Target",         target,                                                    shade=False)
    pdf.kv("Baseline Avg",   f"{base_avg} ms" if base_avg is not None else "unknown",  shade=True)
    pdf.kv("Sustained Avg",  f"{sust_avg} ms" if sust_avg is not None else "unknown",  shade=False)
    pdf.kv_flag("High Jitter",        ind.get("high_jitter",        False), shade=True)
    pdf.kv_flag("Latency Under Load", ind.get("latency_under_load", False), shade=False)
    pdf.kv_flag("Packet Loss",        ind.get("packet_loss",        False), shade=True)
    pdf.kv_flag("Slow Recovery",      ind.get("slow_recovery",      False), shade=False)

    # Stage breakdown table
    # (avg, is_stddev): Jitter reports std deviation, not avg latency
    stage_rows = [
        ("Baseline",     ss.get("baseline",    "?"), baseline.get("avg_latency_ms"),  None,                              False),
        ("Jitter",       ss.get("jitter",      "?"), jitter.get("stddev_ms"),         jitter.get("packet_loss_percent"), True),
        ("Large Packet", ss.get("large_packet","?"), large.get("avg_latency_ms"),     large.get("packet_loss_percent"),  False),
        ("Sustained",    ss.get("sustained",   "?"), sustained.get("avg_latency_ms"), sustained.get("packet_loss_percent"), False),
        ("Recovery",     ss.get("recovery",    "?"), recovery.get("avg_latency_ms"),  None,                              False),
    ]
    # Column widths: 55 + 20 + 50 + 45 = 170
    COL = (55, 20, 50, 45)
    pdf.ln(3)
    # Header row
    pdf.set_fill_color(*C_NAV)
    pdf.set_text_color(*C_WHT)
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_x(pdf.l_margin)
    pdf.cell(COL[0], 5, "  Stage",   fill=True)
    pdf.cell(COL[1], 5, "Status",    fill=True, align="C")
    pdf.cell(COL[2], 5, "Avg",       fill=True, align="R")
    pdf.cell(COL[3], 5, "Loss",      fill=True, align="R", new_x="LMARGIN", new_y="NEXT")
    for i, (stage_name, status, avg, loss, is_stddev) in enumerate(stage_rows):
        row_y = pdf.get_y()
        if i % 2 == 0:
            pdf.set_fill_color(*C_LGR)
            pdf.rect(pdf.l_margin, row_y, 170, 5, "F")
        avg_str  = (f"{avg} ms (\u03c3)" if is_stddev else f"{avg} ms") if avg is not None else "--"
        loss_str = f"{loss}%"   if loss is not None else "--"
        status_s = str(status) if status else "?"
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*C_DGR)
        pdf.set_x(pdf.l_margin)
        pdf.cell(COL[0], 5, safe(f"  {stage_name}"))
        if status_s.lower() == "ok":
            pdf.set_text_color(*C_ADV)
        elif status_s.lower() in ("warn", "warning", "fail", "failed"):
            pdf.set_text_color(*C_HGH)
        pdf.cell(COL[1], 5, safe(status_s), align="C")
        pdf.set_text_color(*C_DGR)
        pdf.cell(COL[2], 5, safe(avg_str),  align="R")
        pdf.cell(COL[3], 5, safe(loss_str), align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*C_DGR)
    if m := data.get("methodology"):
        pdf.note(m)


def render_vlan_trunk(pdf, data):
    pdf.subsection_title("11. VLAN / Trunk Detection")
    vlan_ids = data.get("observed_vlan_ids") or []
    ind      = data.get("indicators") or {}
    pdf.kv("Interface",              data.get("interface"),                         shade=True)
    pdf.kv_flag("Tagged Frames Observed", data.get("tagged_frames_observed", False), shade=False)
    pdf.kv("Observed VLAN IDs",     ", ".join(str(v) for v in vlan_ids) or "none",  shade=True)
    pdf.kv_flag("Trunk Port Suspected",   ind.get("trunk_port_suspected", False),    shade=False)
    pdf.kv_flag("CDP/LLDP Exposure",      ind.get("cdp_exposed",          False),    shade=True)
    pdf.kv_flag("Multiple VLANs Visible", ind.get("multiple_vlans_visible", False),  shade=False)

    cdp  = data.get("cdp_neighbours")  or []
    lldp = data.get("lldp_neighbours") or []

    if cdp:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, safe(f"  CDP Neighbours ({len(cdp)}):"), new_x="LMARGIN", new_y="NEXT")
        for n in cdp:
            vlan = str(n.get("native_vlan")) if n.get("native_vlan") is not None else "unknown"
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*C_MGR)
            pdf.multi_cell(
                0, 4,
                safe(
                    f"    {n.get('device_id','?')}  |  {n.get('platform','?')}"
                    f"  |  Port: {n.get('port_id','?')}  |  Native VLAN: {vlan}"
                    f"  |  Duplex: {n.get('duplex','?')}"
                ),
                new_x="LMARGIN", new_y="NEXT",
            )
        pdf.set_text_color(*C_DGR)
    else:
        pdf.note("CDP Neighbours: none detected")

    if lldp:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, safe(f"  LLDP Neighbours ({len(lldp)}):"), new_x="LMARGIN", new_y="NEXT")
        for n in lldp:
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*C_MGR)
            pdf.multi_cell(
                0, 4,
                safe(
                    f"    {n.get('system_name','?')}  |  Chassis: {n.get('chassis_id','?')}"
                    f"  |  Port: {n.get('port_id','?')}"
                ),
                new_x="LMARGIN", new_y="NEXT",
            )
        pdf.set_text_color(*C_DGR)
    else:
        pdf.note("LLDP Neighbours: none detected")

    probe = data.get("double_tag_probe", "not attempted")
    pdf.kv("Double-Tag Probe", probe, shade=False)


def render_duplicate_ip(pdf, data):
    pdf.subsection_title("12. Duplicate IP Detection")
    network        = data.get("network")          or "unknown"
    iface          = data.get("interface")        or "unknown"
    total_hosts    = data.get("total_hosts_seen", 0)
    duplicate_count= data.get("duplicate_count",  0)
    duplicates     = data.get("duplicates")       or []

    pdf.kv("Interface",        iface,          shade=False)
    pdf.kv("Network Range",    network,        shade=True)
    pdf.kv("Total Hosts Seen", total_hosts,    shade=False)
    pdf.kv_flag("Duplicates Detected", duplicate_count > 0, shade=True)
    pdf.kv("Duplicate IP Count", duplicate_count, shade=False)

    if not duplicates:
        pdf.note("No duplicate IPs detected. All hosts responded with a unique MAC address.")
        return

    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*C_DGR)
    pdf.cell(0, 5, safe(f"  Conflicting Hosts ({duplicate_count}):"), new_x="LMARGIN", new_y="NEXT")
    for dup in duplicates:
        ip   = dup.get("ip",   "unknown")
        macs = dup.get("macs") or []
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*C_HGH)
        pdf.cell(0, 5, safe(f"    {ip}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*C_MGR)
        for mac in macs:
            pdf.cell(0, 4, safe(f"      MAC: {mac}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*C_DGR)


def render_custom_port_scan(pdf, data, index):
    target = data.get("target_ip", "unknown")
    pdf.subsection_title(f"13. Custom Target Port Scan - {target}  (device {index})")
    ports = data.get("open_ports") or []
    pdf.kv("Target IP",       target,                                            shade=False)
    pdf.kv("Open Port Count", str(len(ports)),                                   shade=True)
    pdf.kv("Open TCP Ports",  ", ".join(str(p) for p in ports) or "none",        shade=False)


def render_custom_stress(pdf, data, index):
    target = data.get("target_ip", "unknown")
    render_stress_test(pdf, 14, f"Custom Target Stress Test - {target}  (device {index})", data)


def render_custom_identity(pdf, data, index):
    target = data.get("target_ip", "unknown")
    pdf.subsection_title(f"15. Custom Target Identity Scan - {target}  (device {index})")
    for i, (k, v) in enumerate([
        ("Target IP",       target),
        ("Hostname",        data.get("hostname")),
        ("MAC Address",     data.get("mac_address")),
        ("Vendor",          data.get("vendor")),
        ("Device Type Hint",data.get("device_type_hint")),
        ("Confidence",      data.get("confidence")),
        ("Identity Summary",data.get("identity_summary")),
    ]):
        pdf.kv(k, v, shade=i % 2 == 0)


def render_custom_dns_assessment(pdf, data, index):
    target = data.get("target_ip", "unknown")
    pdf.subsection_title(f"16. Custom DNS Assessment - {target}  (device {index})")
    pdf.kv("Target IP",              target,                                           shade=True)
    pdf.kv_flag("DNS Service Working", data.get("dns_service_working", False),         shade=False)
    pdf.kv_flag("Recursion Available", data.get("recursion_available", False),         shade=True)
    pdf.kv("UDP Query Status",       (data.get("udp_query") or {}).get("status"),     shade=False)
    pdf.kv("TCP Query Status",       (data.get("tcp_query") or {}).get("status"),     shade=True)
    pdf.kv("Software Hint",          data.get("software_hint"),                       shade=False)


def render_wireless_survey(pdf, data):
    pdf.subsection_title("17. Wireless Site Survey")
    survey    = data.get("survey") or []
    iface     = data.get("interface") or "unknown"
    n_rooms   = data.get("rooms_scanned", len(survey))

    pdf.kv("Interface",     iface,   shade=False)
    pdf.kv("Rooms Scanned", n_rooms, shade=True)

    if not survey:
        pdf.note("No room data recorded.")
        return

    # ── Summary table ────────────────────────────────────────────────────
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*C_DGR)
    pdf.cell(0, 5, "  Survey Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    # Column widths (total 170 mm)
    SC = [8, 30, 22, 20, 10, 22, 14, 44]   # #, Building, Floor, Room, AP, Label, Nets, Strongest
    HDRS = ["#", "Building", "Floor", "Room / Area", "AP", "AP Label", "Nets", "Strongest Signal"]

    pdf.set_fill_color(*C_NAV)
    pdf.set_text_color(*C_WHT)
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_x(20)
    for w, h in zip(SC, HDRS):
        pdf.cell(w, 6, safe(f" {h}"), fill=True)
    pdf.ln()

    for idx, room in enumerate(survey):
        nets    = room.get("networks") or []
        top     = sorted(nets, key=lambda n: (n.get("rssi_dbm") is not None, n.get("rssi_dbm", -999)), reverse=True)[:1]
        if top:
            rssi_val = top[0].get("rssi_dbm")
            sig_str  = f"{rssi_val} dBm" if rssi_val is not None else "--"
            strongest = f"{top[0].get('ssid') or '(hidden)'} ({sig_str})"
        else:
            strongest = "--"
        ap_flag = "Yes" if room.get("ap_present") else "No"
        ap_lbl  = room.get("ap_label") or "--"
        row_vals = [
            str(idx + 1),
            room.get("building") or "--",
            room.get("floor")    or "--",
            room.get("room")     or "--",
            ap_flag,
            ap_lbl,
            str(len(nets)),
            strongest,
        ]
        shade = idx % 2 == 0
        if shade:
            pdf.set_fill_color(*C_LGR)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*C_DGR)
        pdf.set_x(20)
        for w, v in zip(SC, row_vals):
            pdf.cell(w, 5, safe(f" {v}"), fill=shade)
        pdf.ln()

    # ── Per-room detail ──────────────────────────────────────────────────
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*C_DGR)
    pdf.cell(0, 5, "  Room Detail  (top 5 networks by signal strength)", new_x="LMARGIN", new_y="NEXT")

    for room in survey:
        building = room.get("building") or "--"
        floor    = room.get("floor")    or "--"
        rm       = room.get("room")     or "--"
        ap_txt   = "Yes" if room.get("ap_present") else "No"
        ap_lbl   = room.get("ap_label") or "--"
        nets     = room.get("networks") or []
        top5     = sorted(nets, key=lambda n: (n.get("rssi_dbm") is not None, n.get("rssi_dbm", -999)), reverse=True)[:5]

        pdf.ln(3)
        # Room header bar
        pdf.set_fill_color(*C_SBL)
        pdf.set_text_color(*C_NAV)
        pdf.set_font("Helvetica", "B", 8)
        pdf.multi_cell(0, 6, safe(f"  {building}  |  Floor: {floor}  |  {rm}"), fill=True,
                       new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*C_DGR)

        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_x(20)
        pdf.cell(30, 5, safe("  AP Present:"))
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*(C_HGH if room.get("ap_present") else C_ADV))
        pdf.cell(20, 5, safe(ap_txt), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*C_DGR)

        if ap_lbl and ap_lbl != "--":
            pdf.set_font("Helvetica", "", 7.5)
            pdf.set_x(20)
            pdf.cell(30, 5, safe("  AP Label:"))
            pdf.set_font("Helvetica", "B", 7.5)
            pdf.cell(60, 5, safe(ap_lbl), new_x="LMARGIN", new_y="NEXT")

        pdf.ln(1)

        if not top5:
            pdf.set_font("Helvetica", "I", 7)
            pdf.set_text_color(*C_MGR)
            pdf.cell(0, 4, "  No networks detected in this room.", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(*C_DGR)
            continue

        # Network table — cols: SSID, Signal, Ch, Band, Width, PHY, Security (170mm)
        NC    = [50, 18, 10, 14, 14, 32, 32]
        N_HDRS= ["SSID", "Signal", "Ch", "Band", "Width", "PHY Mode", "Security"]

        pdf.set_fill_color(*C_NAV)
        pdf.set_text_color(*C_WHT)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_x(20)
        for w, h in zip(NC, N_HDRS):
            pdf.cell(w, 5, safe(f" {h}"), fill=True)
        pdf.ln()

        for ni, net in enumerate(top5):
            shade = ni % 2 == 0
            if shade:
                pdf.set_fill_color(*C_LGR)
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*C_DGR)
            rssi  = net.get("rssi_dbm")
            sig   = f"{rssi} dBm" if rssi is not None else "--"
            row_vals = [
                net.get("ssid")          or "(hidden)",
                sig,
                str(net.get("channel")   or "--"),
                net.get("band")          or "--",
                net.get("channel_width") or "--",
                net.get("phy_mode")      or "--",
                net.get("security")      or "--",
            ]
            pdf.set_x(20)
            for w, v in zip(NC, row_vals):
                pdf.cell(w, 5, safe(f" {v}"), fill=shade)
            pdf.ln()

    pdf.set_text_color(*C_DGR)


# ── About This Report page ────────────────────────────────────────────────
TASK_DESCRIPTIONS = [
    (  1, "Interface & Network Info",
       "Identifies the network interface, IP address, subnet, gateway, and MAC address of "
       "the audited device. Also detects whether the scan is being run inside a virtual machine, "
       "which may affect what is visible on the network."),
    (  2, "Internet Speed Test",
       "Measures the actual download speed, upload speed, and round-trip latency of the internet "
       "connection at the time of the audit using a public speed test server."),
    (  3, "Gateway Scan",
       "Scans all TCP ports on the network's gateway (router or firewall) to identify which "
       "services are reachable from the local network. Open management interfaces or monitoring "
       "agents that are not restricted to authorised hosts are flagged."),
    (  4, "DHCP Scan",
       "Discovers which devices on the network are handing out IP addresses. Detects potential "
       "rogue DHCP servers — unauthorised devices that could redirect network traffic to "
       "attacker-controlled destinations by providing false gateway or DNS information."),
    (  5, "DHCP Response Time",
       "Measures how quickly the DHCP server responds to new connection requests. Slow responses "
       "cause delays and failures when devices boot, reconnect, or renew their IP address lease."),
    (  6, "DNS Network Scan",
       "Identifies devices on the network that are responding to DNS queries. Unexpected DNS "
       "responders can silently redirect web and application traffic to malicious destinations."),
    (  7, "LDAP / Active Directory Scan",
       "Detects Active Directory domain controllers and the directory services they expose, "
       "including LDAP, LDAPS, Kerberos, and Global Catalog ports. Confirms whether a Windows "
       "domain infrastructure is present and characterises its service profile."),
    (  8, "SMB / NFS Network Scan",
       "Discovers file-sharing services on the network. Checks whether Windows SMB shares enforce "
       "message signing — without it, traffic is vulnerable to relay attacks. Also detects Linux "
       "NFS exports that are accessible without authentication."),
    (  9, "Printer / Print Server Scan",
       "Locates printers on the network and checks whether the raw printing port (JetDirect, "
       "port 9100) is open without authentication. Unauthenticated printing ports allow "
       "unauthorised print jobs and, on some models, retrieval of previously printed documents."),
    ( 10, "Gateway Stress Test",
       "Sends staged bursts of ICMP traffic to the gateway and measures how latency and packet "
       "loss change under load. Identifies whether the firewall or router degrades significantly "
       "under real network pressure, which may indicate hardware limitations or misconfiguration."),
    ( 11, "VLAN / Trunk Detection",
       "Passively listens for 802.1Q VLAN-tagged frames and Cisco/LLDP neighbour discovery "
       "messages. Determines whether the audited port is connected to a network trunk or can "
       "observe traffic from multiple network segments — a potential isolation weakness."),
    ( 12, "Duplicate IP Detection",
       "Scans the entire network using ARP to find any IP address being claimed by more than "
       "one device. Duplicate IPs cause intermittent connectivity issues and can indicate "
       "IP address conflicts or ARP spoofing."),
    ( 17, "Wireless Site Survey",
       "A room-by-room Wi-Fi survey of the site. For each room the auditor records whether an "
       "access point is physically present, its label, and a live scan of all visible networks "
       "including signal strength, channel, and security mode. Designed for walk-through surveys "
       "of schools, offices, and multi-floor buildings."),
]

CUSTOM_TASK_NOTE = (
    "Additional tasks (13–16) may also appear in this report: custom port scans and stress tests "
    "against specific target devices, identity resolution, and DNS resolver assessment. "
    "These are run selectively based on the scope agreed with the client."
)


def _about_table_header(pdf, col):
    """Draw the about-page table column headers at the current Y position."""
    pdf.set_fill_color(*C_NAV)
    pdf.set_text_color(*C_WHT)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_x(20)
    pdf.cell(col[0], 6, "  #",  fill=True)
    pdf.cell(col[1], 6, "Task", fill=True)
    pdf.cell(col[2], 6, "What it checks and why it matters", fill=True,
             new_x="LMARGIN", new_y="NEXT")


def _measure_row_h(pdf, desc, col_w, line_h):
    """Return the row height needed to fit desc in col_w mm at the current font."""
    words = safe(desc).split()
    lines, line_w = 1, 0.0
    for word in words:
        w = pdf.get_string_width(word + " ")
        if line_w + w > col_w - 1:
            lines += 1
            line_w = w
        else:
            line_w += w
    return max(10.0, lines * line_h + 5)


def render_about_report(pdf, ran_task_ids=None):
    C_ACC      = (74, 144, 226)
    COL        = (12, 52, 106)
    LINE_H     = 3.8
    PAGE_SAFE  = 272   # stop drawing rows below this Y (297mm - ~25mm safety)

    pdf.add_page()
    pdf.set_auto_page_break(False)   # handle page breaks manually for the table

    pdf.section_title("About This Report")

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*C_DGR)
    pdf.set_x(20)
    pdf.multi_cell(
        170, 4.5,
        safe("This report was produced by LSS Network Tools (LS Solutions Software). "
             "Each section below corresponds to a specific test run on the client's network. "
             "The table explains what each task checks and why it matters."),
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.ln(2)
    _about_table_header(pdf, COL)

    # Only describe tasks that were actually run in this report
    visible = [t for t in TASK_DESCRIPTIONS
               if ran_task_ids is None or t[0] in ran_task_ids]

    for i, (num, name, desc) in enumerate(visible):
        pdf.set_font("Helvetica", "", 7)
        row_h = _measure_row_h(pdf, desc, COL[2], LINE_H)

        # If this row won't fit, start a new page and redraw the header
        if pdf.get_y() + row_h > PAGE_SAFE:
            pdf.add_page()
            pdf.set_auto_page_break(False)
            _about_table_header(pdf, COL)

        row_y = pdf.get_y()

        # Row background
        pdf.set_fill_color(*C_LGR if i % 2 == 0 else (250, 251, 254))
        pdf.rect(20, row_y, sum(COL), row_h, "F")

        # Left accent stripe
        if   num <= 3: stripe = C_INF
        elif num <= 6: stripe = C_ADV
        elif num <= 9: stripe = C_WRN
        else:          stripe = (130, 80, 180)
        pdf.set_fill_color(*stripe)
        pdf.rect(20, row_y, 2, row_h, "F")

        mid_y = row_y + (row_h - 5) / 2

        # Task number
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*C_NAV)
        pdf.set_xy(22, mid_y)
        pdf.cell(COL[0] - 2, 5, safe(str(num)), align="C")

        # Task name
        pdf.set_xy(20 + COL[0], mid_y)
        pdf.cell(COL[1], 5, safe(name), align="L")

        # Description — vertically centred within the row
        desc_lines  = max(1, round((row_h - 5) / LINE_H))
        desc_top_y  = row_y + (row_h - desc_lines * LINE_H) / 2
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*C_DGR)
        pdf.set_xy(20 + COL[0] + COL[1], desc_top_y)
        pdf.multi_cell(COL[2], LINE_H, safe(desc), new_x="LMARGIN", new_y="NEXT")

        pdf.set_y(row_y + row_h)   # always advance to exact row bottom

    # Footer note
    pdf.ln(3)
    if pdf.get_y() + 12 > PAGE_SAFE:
        pdf.add_page()
        pdf.set_auto_page_break(False)
    pdf.set_draw_color(*C_ACC)
    pdf.set_line_width(0.4)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*C_MGR)
    pdf.set_x(20)
    custom_ran = ran_task_ids is not None and bool(ran_task_ids & {13, 14, 15, 16})
    if custom_ran:
        footer_note = (
            "Custom tasks (13\u201316) were also run as part of this engagement and appear "
            "in the audit results section: custom port scans, stress tests, identity "
            "resolution, and DNS resolver assessment."
        )
    else:
        footer_note = CUSTOM_TASK_NOTE
    pdf.multi_cell(170, 4.5, safe(footer_note), new_x="LMARGIN", new_y="NEXT")

    pdf.set_auto_page_break(True, margin=20)


# ── Main ──────────────────────────────────────────────────────────────────
def main():
    if len(sys.argv) < 3:
        print("Usage: generate_pdf_report.py <run_output_dir> <app_root>", file=sys.stderr)
        sys.exit(1)

    run_dir  = Path(sys.argv[1])
    app_root = Path(sys.argv[2])
    pdf_path_override = Path(sys.argv[3]) if len(sys.argv) > 3 and sys.argv[3] else None
    prepared_by_arg   = sys.argv[4] if len(sys.argv) > 4 else ""
    logo     = app_root / "assets" / "logo.png"

    manifest        = load_json(run_dir / "manifest.json")        or {}
    findings_data   = load_json(run_dir / "findings.json")        or {}
    remediation_data= load_json(run_dir / "remediation.json")     or {}

    client      = manifest.get("client",       "Unknown Client")
    location    = manifest.get("location",     "Unknown Location")
    note        = manifest.get("note",         "")
    date_stamp  = manifest.get("generated_at", "Unknown Date")
    prepared_by = prepared_by_arg or manifest.get("prepared_by",  "")

    pdf = Report(
        client      = client,
        location    = location,
        note        = note,
        date_stamp  = date_stamp,
        prepared_by = prepared_by,
        logo_path   = str(logo) if logo.exists() else None,
    )
    pdf.add_page()
    pdf.cover()

    # ── About This Report ─────────────────────────────────────────────────
    ran_task_ids = {
        t["task_id"]
        for t in manifest.get("tasks", [])
        if t.get("json_present")
    }
    # Pass None when the set is empty so render_about_report shows all tasks
    # as a safe fallback rather than an empty table.
    render_about_report(pdf, ran_task_ids or None)

    # ── Executive Summary ──────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Executive Summary - Key Findings")
    _SEV_ORDER = {"high": 0, "warning": 1, "info": 2, "advice": 3}
    findings = sorted(
        findings_data.get("findings") or [],
        key=lambda f: _SEV_ORDER.get(f.get("severity", "info").lower(), 99),
    )
    if not findings:
        pdf.note("No notable findings were generated from this scan set.")
    else:
        for i, f in enumerate(findings):
            pdf.finding_row(
                f.get("severity", "info"),
                f.get("title",    ""),
                f.get("detail",   ""),
                shade=i % 2 == 0,
            )

    # ── Remediation Hints ──────────────────────────────────────────────────
    hints = remediation_data.get("hints") or []
    if hints:
        pdf.section_title("Remediation Hints")
        for i, h in enumerate(hints):
            pdf.hint_row(h.get("title", ""), h.get("detail", ""), shade=i % 2 == 0)

    # ── Audit Results ──────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Audit Results - Per Task")

    def get(task_id):
        p = task_json_path(run_dir, manifest, task_id)
        return load_json(p) if p and p.exists() else None

    if d := get(1):  render_interface_info(pdf, d)
    if d := get(2):  render_speed_test(pdf, d)
    if d := get(3):  render_gateway(pdf, d)
    if d := get(4):  render_dhcp(pdf, d)
    if d := get(5):  render_dhcp_response_time(pdf, d)
    if d := get(6):  render_generic_scan(pdf, 6,  "DNS Network Scan",              d)
    if d := get(7):  render_generic_scan(pdf, 7,  "LDAP/AD Network Scan",          d)
    if d := get(8):  render_smb_nfs(pdf, d)
    if d := get(9):  render_generic_scan(pdf, 9,  "Printer/Print Server Network Scan", d)
    if d := get(10): render_stress_test(pdf, 10,  "Gateway Stress Test",           d)
    if d := get(11): render_vlan_trunk(pdf, d)
    if d := get(12): render_duplicate_ip(pdf, d)

    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 13), 1):
        if d := load_json(p): render_custom_port_scan(pdf, d, i)
    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 14), 1):
        if d := load_json(p): render_custom_stress(pdf, d, i)
    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 15), 1):
        if d := load_json(p): render_custom_identity(pdf, d, i)
    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 16), 1):
        if d := load_json(p): render_custom_dns_assessment(pdf, d, i)

    if d := get(17): render_wireless_survey(pdf, d)

    # ── Output path ────────────────────────────────────────────────────────
    if pdf_path_override:
        pdf_path = pdf_path_override
    else:
        report_txt = manifest.get("report_file", "")
        if report_txt:
            pdf_path = run_dir / (Path(report_txt).stem + ".pdf")
        else:
            def slug(s): return s.lower().replace(" ", "-")
            pdf_path = run_dir / f"lss-network-tools-report-{slug(client)}-{slug(location)}.pdf"

    pdf.output(str(pdf_path))
    print(str(pdf_path))


if __name__ == "__main__":
    main()
