#!/usr/bin/env python3
"""LSS Network Tools -- PDF Report Generator"""

import sys
import os
import json
from pathlib import Path

try:
    from fpdf import FPDF
except ImportError:
    print("fpdf2 is not installed. Install with: pip3 install fpdf2", file=sys.stderr)
    sys.exit(1)

# ── Colour palette ─────────────────────────────────────────────────────────
C_NAV  = (26,  42,  74)    # dark navy
C_WHT  = (255, 255, 255)   # white
C_LGR  = (245, 245, 245)   # light gray (alt rows)
C_DGR  = (33,  33,  33)    # near-black body text
C_MGR  = (117, 117, 117)   # muted / secondary text
C_SBL  = (232, 240, 254)   # section sub-header bg (light blue)
C_HGH  = (211, 47,  47)    # red   -- HIGH
C_WRN  = (245, 124,  0)    # orange -- WARNING
C_INF  = (25,  118, 210)   # blue  -- INFO
C_ADV  = (56,  142,  60)   # green -- ADVICE

SEV_COLORS = {
    "high":    C_HGH,
    "warning": C_WRN,
    "info":    C_INF,
    "advice":  C_ADV,
}


# ── PDF class ──────────────────────────────────────────────────────────────
class Report(FPDF):
    def __init__(self, client, location, note, date_stamp, prepared_by, logo_path):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.client      = client
        self.location    = location
        self.run_note    = note
        self.date_stamp  = date_stamp
        self.prepared_by = prepared_by
        self.logo_path   = logo_path
        self._cover_done = False
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 20, 20)

    def header(self):
        if not self._cover_done:
            return
        self.set_fill_color(*C_NAV)
        self.rect(0, 0, 210, 12, "F")
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*C_WHT)
        self.set_xy(8, 3)
        self.cell(
            0, 6,
            safe(f"LSS Network Tools  |  {self.client}  /  {self.location}  |  {self.date_stamp}"),
            align="L",
        )
        self.set_text_color(*C_DGR)
        self.set_y(18)

    def footer(self):
        if not self._cover_done:
            return
        self.set_y(-13)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*C_MGR)
        self.cell(
            0, 6,
            safe(f"Page {self.page_no()}  --  Generated by LSS Network Tools (LS Solutions Software)"),
            align="C",
        )

    # ── Cover page ──────────────────────────────────────────────────────────
    def cover(self):
        # Top navy bar
        self.set_fill_color(*C_NAV)
        self.rect(0, 0, 210, 70, "F")

        # Logo -- top-right inside the bar
        logo_rendered = False
        if self.logo_path and os.path.exists(self.logo_path):
            try:
                self.image(self.logo_path, x=152, y=5, w=48)
                logo_rendered = True
            except Exception:
                pass
        if not logo_rendered:
            self.set_font("Helvetica", "B", 22)
            self.set_text_color(*C_WHT)
            self.set_xy(148, 20)
            self.cell(50, 14, safe(self.client[:6] if self.client else "LSS"), align="C")

        # Title
        self.set_font("Helvetica", "B", 24)
        self.set_text_color(*C_WHT)
        self.set_xy(20, 18)
        self.cell(125, 12, "Network Audit Report", align="L")
        self.set_font("Helvetica", "", 11)
        self.set_xy(20, 33)
        self.cell(125, 7, "Generated by LSS Network Tools (LS Solutions Software)", align="L")

        # Metadata card
        self.set_fill_color(*C_LGR)
        self.set_draw_color(*C_NAV)
        rows = [
            ("Client",      self.client),
            ("Location",    self.location),
        ]
        if self.run_note:
            rows.append(("Note", self.run_note))
        rows.append(("Date", self.date_stamp))
        if self.prepared_by:
            rows.append(("Prepared By", self.prepared_by))
        row_h   = 5
        row_gap = 7
        card_top = 76
        card_h  = row_gap * len(rows) + 8
        self.rect(20, card_top, 170, card_h, "FD")
        self.set_text_color(*C_DGR)

        for i, (k, v) in enumerate(rows):
            y = card_top + 5 + i * row_gap
            self.set_font("Helvetica", "B", 9)
            self.set_xy(28, y)
            self.cell(38, row_h, safe(k + ":"), align="L")
            self.set_font("Helvetica", "", 9)
            self.cell(0, row_h, safe(str(v)), align="L")

        self.set_y(card_top + card_h + 8)
        self._cover_done = True

    # ── Layout helpers ──────────────────────────────────────────────────────
    def section_title(self, title):
        self.ln(5)
        self.set_fill_color(*C_NAV)
        self.set_text_color(*C_WHT)
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 8, safe(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)
        self.ln(2)

    def subsection_title(self, title):
        self.ln(3)
        self.set_fill_color(*C_SBL)
        self.set_text_color(*C_NAV)
        self.set_font("Helvetica", "B", 9)
        self.cell(0, 7, safe(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)
        self.ln(1)

    def kv(self, key, value, shade=False):
        self.set_x(self.l_margin)
        if shade:
            self.set_fill_color(*C_LGR)
        self.set_font("Helvetica", "B", 8)
        self.cell(52, 5, safe(f"  {key}"), fill=shade)
        self.set_font("Helvetica", "", 8)
        val_w = self.w - self.l_margin - self.r_margin - 52
        self.multi_cell(val_w, 5, safe(str(value) if value is not None else "--"), fill=shade,
                        new_x="LMARGIN", new_y="NEXT")

    def finding_row(self, severity, title, detail, shade=False):
        color = SEV_COLORS.get(severity.lower(), C_MGR)
        if shade:
            self.set_fill_color(*C_LGR)
            self.rect(self.l_margin, self.get_y(), 170, 5, "F")
        # Severity badge
        self.set_fill_color(*color)
        self.set_text_color(*C_WHT)
        self.set_font("Helvetica", "B", 7)
        self.cell(22, 5, safe(severity.upper()), fill=True, align="C")
        # Title on same line
        self.set_text_color(*C_DGR)
        self.set_font("Helvetica", "B", 8)
        self.cell(148, 5, safe(f"  {title}"), new_x="LMARGIN", new_y="NEXT")
        # Detail indented
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*C_MGR)
        self.set_x(self.l_margin + 24)
        self.multi_cell(146, 4, safe(detail), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)
        self.ln(1)

    def hint_row(self, title, detail, shade=False):
        if shade:
            self.set_fill_color(*C_LGR)
            self.set_font("Helvetica", "B", 8)
            self.cell(170, 5, safe(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        else:
            # Accent bar on the left for unshaded rows
            bar_y = self.get_y()
            self.set_font("Helvetica", "B", 8)
            self.cell(170, 5, safe(f"  {title}"), fill=False, new_x="LMARGIN", new_y="NEXT")
            self.set_draw_color(*C_NAV)
            self.set_line_width(0.6)
            self.line(self.l_margin, bar_y, self.l_margin, bar_y + 5)
            self.set_line_width(0.2)
        self.set_font("Helvetica", "B", 8)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*C_MGR)
        self.set_x(self.l_margin + 4)
        self.multi_cell(166, 4, safe(detail), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)
        self.ln(1)

    def kv_flag(self, key, value, shade=False):
        """Like kv() but renders boolean True/False with colour (red/green)."""
        self.set_x(self.l_margin)
        if shade:
            self.set_fill_color(*C_LGR)
        self.set_font("Helvetica", "B", 8)
        self.cell(52, 5, safe(f"  {key}"), fill=shade)
        bool_val = value is True or str(value).lower() == "true"
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*(C_HGH if bool_val else C_ADV))
        val_w = self.w - self.l_margin - self.r_margin - 52
        self.multi_cell(val_w, 5, "Yes" if bool_val else "No",
                        fill=shade, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)

    def note(self, text):
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*C_MGR)
        self.cell(0, 5, safe(f"  {text}"), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*C_DGR)


# ── Text helpers ──────────────────────────────────────────────────────────
def safe(text):
    """Strip characters outside latin-1 so Helvetica never crashes."""
    if text is None:
        return "--"
    return str(text).encode("latin-1", errors="replace").decode("latin-1")


# ── Data helpers ──────────────────────────────────────────────────────────
def load_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def task_json_path(run_dir, manifest, task_id):
    """Return Path to the primary JSON for a given task_id, or None."""
    for t in manifest.get("tasks", []):
        try:
            if int(t.get("task_id", -1)) == task_id:
                files = t.get("json_files") or []
                if files:
                    return run_dir / files[0]
                jf = t.get("json_file")
                if jf:
                    return run_dir / jf
        except (TypeError, ValueError):
            continue
    return None


def all_task_json_paths(run_dir, manifest, task_id):
    """Return list of existing Paths for all JSON files of a multi-entry task."""
    for t in manifest.get("tasks", []):
        try:
            if int(t.get("task_id", -1)) == task_id:
                return [
                    run_dir / f
                    for f in (t.get("json_files") or [])
                    if (run_dir / f).exists()
                ]
        except (TypeError, ValueError):
            continue
    return []


# ── Task renderers ────────────────────────────────────────────────────────
def render_interface_info(pdf, data):
    pdf.subsection_title("1. Interface Network Info")
    for i, (k, v) in enumerate([
        ("Interface",    data.get("interface")),
        ("IP Address",   data.get("ip_address")),
        ("Subnet Mask",  data.get("subnet")),
        ("Network Range",data.get("network")),
        ("Gateway",      data.get("gateway")),
        ("MAC Address",  data.get("mac_address")),
    ]):
        pdf.kv(k, v or "unknown", shade=i % 2 == 0)


def render_speed_test(pdf, data):
    pdf.subsection_title("2. Internet Speed Test")
    srv   = (data.get("servers") or [{}])[0]
    ping  = srv.get("ping_ms")
    dl    = srv.get("download_mbps")
    ul    = srv.get("upload_mbps")
    for i, (k, v) in enumerate([
        ("Public IP",   srv.get("public_ip") or data.get("public_ip")),
        ("Test Server", srv.get("test_server") or srv.get("server_name")),
        ("Ping",        f"{ping} ms"   if ping is not None else "unknown"),
        ("Download",    f"{dl} Mbps"   if dl   is not None else "unknown"),
        ("Upload",      f"{ul} Mbps"   if ul   is not None else "unknown"),
    ]):
        pdf.kv(k, v or "unknown", shade=i % 2 == 0)


def render_gateway(pdf, data):
    pdf.subsection_title("3. Gateway Details")
    ports = data.get("open_ports") or []
    pdf.kv("Gateway IP",      data.get("gateway_ip", "unknown"), shade=False)
    pdf.kv("Open Port Count", str(len(ports)),                   shade=True)
    pdf.kv("Open TCP Ports",  ", ".join(str(p) for p in ports) or "none", shade=False)


def render_dhcp(pdf, data):
    pdf.subsection_title("4. DHCP Network Scan")
    relay_raw = data.get("relay_sources_seen") or []
    relay = ", ".join(relay_raw) or "none"
    for i, (k, v) in enumerate([
        ("Discovery Attempts",   data.get("discovery_attempts")),
        ("Responders Observed",  data.get("dhcp_responders_observed", 0)),
        ("Unique Offers",        data.get("offers_observed", 0)),
        ("Raw Offers Captured",  data.get("raw_offers_observed", 0)),
        ("Rogue DHCP Suspected", data.get("rogue_dhcp_suspected", False)),
        ("Relay / Proxy Sources",relay),
    ]):
        pdf.kv(k, v, shade=i % 2 == 0)
    responder_ips = {srv.get("ip") for srv in (data.get("servers") or [])}
    relay_only = [ip for ip in relay_raw if ip not in responder_ips]
    if relay_only:
        pdf.note(f"Relay/proxy only (no DHCP offers issued): {', '.join(relay_only)}")
    for ip in data.get("suspected_rogue_servers") or []:
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*C_HGH)
        pdf.cell(0, 5, safe(f"  ! Suspected rogue responder: {ip}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*C_DGR)
    servers = data.get("servers") or []
    if servers:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, f"  DHCP Responders ({len(servers)}):", new_x="LMARGIN", new_y="NEXT")
        for srv in servers:
            ports = ", ".join(str(p) for p in (srv.get("open_ports") or [])) or "none"
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*C_MGR)
            pdf.set_x(pdf.l_margin + 4)
            pdf.multi_cell(
                166, 4,
                safe(f"{srv.get('ip','?')}  |  Class: {srv.get('classification','unknown')}"
                     f"  |  Offers: {srv.get('offers_observed',0)}"
                     f"  |  Rogue: {srv.get('suspected_rogue', False)}"
                     f"  |  Ports: {ports}"),
                new_x="LMARGIN", new_y="NEXT",
            )
        pdf.set_text_color(*C_DGR)


def render_generic_scan(pdf, num, title, data):
    pdf.subsection_title(f"{num}. {title}")
    network    = data.get("network") or "unknown"
    scan_ports = data.get("scan_ports") or "unknown"
    servers    = data.get("servers") or []
    pdf.kv("Network Range",  network,    shade=False)
    pdf.kv("Scanned Ports",  scan_ports, shade=True)
    pdf.kv("Servers Found",  len(servers), shade=False)
    if not servers:
        pdf.note("No hosts detected.")
        return
    pdf.ln(1)
    for srv in servers:
        ip       = srv.get("ip", "unknown")
        ports    = ", ".join(str(p) for p in (srv.get("open_ports") or [])) or "none"
        services = ", ".join(srv.get("detected_services") or []) or "unknown"
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*C_DGR)
        pdf.cell(0, 5, safe(f"  {ip}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*C_MGR)
        pdf.cell(0, 4, safe(f"    Ports: {ports}   |   Services: {services}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*C_DGR)


def render_stress_test(pdf, num, label, data):
    pdf.subsection_title(f"{num}. {label}")
    target     = data.get("gateway") or data.get("target_ip") or data.get("gateway_ip", "unknown")
    ind        = data.get("indicators") or {}
    ss         = data.get("stage_status") or {}
    baseline   = data.get("baseline")         or {}
    jitter     = data.get("jitter_test")      or {}
    large      = data.get("large_packet_test") or {}
    sustained  = data.get("sustained_test")   or {}
    recovery   = data.get("recovery")         or {}

    base_avg = baseline.get("avg_latency_ms")
    sust_avg = sustained.get("avg_latency_ms")

    pdf.kv("Target",         target,                                                    shade=False)
    pdf.kv("Baseline Avg",   f"{base_avg} ms" if base_avg is not None else "unknown",  shade=True)
    pdf.kv("Sustained Avg",  f"{sust_avg} ms" if sust_avg is not None else "unknown",  shade=False)
    pdf.kv_flag("High Jitter",        ind.get("high_jitter",        False), shade=True)
    pdf.kv_flag("Latency Under Load", ind.get("latency_under_load", False), shade=False)
    pdf.kv_flag("Packet Loss",        ind.get("packet_loss",        False), shade=True)
    pdf.kv_flag("Slow Recovery",      ind.get("slow_recovery",      False), shade=False)

    # Stage breakdown table
    # (avg, is_stddev): Jitter reports std deviation, not avg latency
    stage_rows = [
        ("Baseline",     ss.get("baseline",    "?"), baseline.get("avg_latency_ms"),  None,                              False),
        ("Jitter",       ss.get("jitter",      "?"), jitter.get("stddev_ms"),         jitter.get("packet_loss_percent"), True),
        ("Large Packet", ss.get("large_packet","?"), large.get("avg_latency_ms"),     large.get("packet_loss_percent"),  False),
        ("Sustained",    ss.get("sustained",   "?"), sustained.get("avg_latency_ms"), sustained.get("packet_loss_percent"), False),
        ("Recovery",     ss.get("recovery",    "?"), recovery.get("avg_latency_ms"),  None,                              False),
    ]
    # Column widths: 55 + 20 + 50 + 45 = 170
    COL = (55, 20, 50, 45)
    pdf.ln(3)
    # Header row
    pdf.set_fill_color(*C_NAV)
    pdf.set_text_color(*C_WHT)
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_x(pdf.l_margin)
    pdf.cell(COL[0], 5, "  Stage",   fill=True)
    pdf.cell(COL[1], 5, "Status",    fill=True, align="C")
    pdf.cell(COL[2], 5, "Avg",       fill=True, align="R")
    pdf.cell(COL[3], 5, "Loss",      fill=True, align="R", new_x="LMARGIN", new_y="NEXT")
    for i, (stage_name, status, avg, loss, is_stddev) in enumerate(stage_rows):
        row_y = pdf.get_y()
        if i % 2 == 0:
            pdf.set_fill_color(*C_LGR)
            pdf.rect(pdf.l_margin, row_y, 170, 5, "F")
        avg_str  = (f"{avg} ms (\u03c3)" if is_stddev else f"{avg} ms") if avg is not None else "--"
        loss_str = f"{loss}%"   if loss is not None else "--"
        status_s = str(status) if status else "?"
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*C_DGR)
        pdf.set_x(pdf.l_margin)
        pdf.cell(COL[0], 5, safe(f"  {stage_name}"))
        if status_s.lower() == "ok":
            pdf.set_text_color(*C_ADV)
        elif status_s.lower() in ("warn", "warning", "fail", "failed"):
            pdf.set_text_color(*C_HGH)
        pdf.cell(COL[1], 5, safe(status_s), align="C")
        pdf.set_text_color(*C_DGR)
        pdf.cell(COL[2], 5, safe(avg_str),  align="R")
        pdf.cell(COL[3], 5, safe(loss_str), align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*C_DGR)


def render_vlan_trunk(pdf, data):
    pdf.subsection_title("10. VLAN / Trunk Detection")
    vlan_ids = data.get("observed_vlan_ids") or []
    ind      = data.get("indicators") or {}
    for i, (k, v) in enumerate([
        ("Interface",            data.get("interface")),
        ("Tagged Frames Observed",data.get("tagged_frames_observed", False)),
        ("Observed VLAN IDs",    ", ".join(str(v) for v in vlan_ids) or "none"),
        ("Trunk Port Suspected", ind.get("trunk_port_suspected", False)),
        ("CDP/LLDP Exposure",    ind.get("cdp_exposed",          False)),
        ("Multiple VLANs Visible",ind.get("multiple_vlans_visible", False)),
    ]):
        pdf.kv(k, v, shade=i % 2 == 0)

    cdp  = data.get("cdp_neighbours")  or []
    lldp = data.get("lldp_neighbours") or []

    if cdp:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, safe(f"  CDP Neighbours ({len(cdp)}):"), new_x="LMARGIN", new_y="NEXT")
        for n in cdp:
            vlan = str(n.get("native_vlan")) if n.get("native_vlan") is not None else "unknown"
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*C_MGR)
            pdf.cell(
                0, 4,
                safe(
                    f"    {n.get('device_id','?')}  |  {n.get('platform','?')}"
                    f"  |  Port: {n.get('port_id','?')}  |  Native VLAN: {vlan}"
                    f"  |  Duplex: {n.get('duplex','?')}"
                ),
                new_x="LMARGIN", new_y="NEXT",
            )
        pdf.set_text_color(*C_DGR)
    else:
        pdf.note("CDP Neighbours: none detected")

    if lldp:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, safe(f"  LLDP Neighbours ({len(lldp)}):"), new_x="LMARGIN", new_y="NEXT")
        for n in lldp:
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*C_MGR)
            pdf.cell(
                0, 4,
                safe(
                    f"    {n.get('system_name','?')}  |  Chassis: {n.get('chassis_id','?')}"
                    f"  |  Port: {n.get('port_id','?')}"
                ),
                new_x="LMARGIN", new_y="NEXT",
            )
        pdf.set_text_color(*C_DGR)
    else:
        pdf.note("LLDP Neighbours: none detected")

    probe = data.get("double_tag_probe", "not attempted")
    pdf.kv("Double-Tag Probe", probe, shade=False)


def render_custom_port_scan(pdf, data, index):
    target = data.get("target_ip", "unknown")
    pdf.subsection_title(f"11. Custom Target Port Scan - {target}  (device {index})")
    ports = data.get("open_ports") or []
    pdf.kv("Target IP",       target,                                            shade=False)
    pdf.kv("Open Port Count", str(len(ports)),                                   shade=True)
    pdf.kv("Open TCP Ports",  ", ".join(str(p) for p in ports) or "none",        shade=False)


def render_custom_stress(pdf, data, index):
    target = data.get("target_ip", "unknown")
    render_stress_test(pdf, 12, f"Custom Target Stress Test - {target}  (device {index})", data)


def render_custom_identity(pdf, data, index):
    target = data.get("target_ip", "unknown")
    pdf.subsection_title(f"13. Custom Target Identity Scan - {target}  (device {index})")
    for i, (k, v) in enumerate([
        ("Target IP",       target),
        ("Hostname",        data.get("hostname")),
        ("MAC Address",     data.get("mac_address")),
        ("Vendor",          data.get("vendor")),
        ("Device Type Hint",data.get("device_type_hint")),
        ("Confidence",      data.get("confidence")),
        ("Identity Summary",data.get("identity_summary")),
    ]):
        pdf.kv(k, v, shade=i % 2 == 0)


def render_custom_dns_assessment(pdf, data, index):
    target = data.get("target_ip", "unknown")
    pdf.subsection_title(f"14. Custom DNS Assessment - {target}  (device {index})")
    for i, (k, v) in enumerate([
        ("Target IP",          target),
        ("DNS Service Working", data.get("dns_service_working", False)),
        ("Recursion Available", data.get("recursion_available", False)),
        ("UDP Query Status",    (data.get("udp_query") or {}).get("status")),
        ("TCP Query Status",    (data.get("tcp_query") or {}).get("status")),
        ("Software Hint",       data.get("software_hint")),
    ]):
        pdf.kv(k, v, shade=i % 2 == 0)


# ── Main ──────────────────────────────────────────────────────────────────
def main():
    if len(sys.argv) < 3:
        print("Usage: generate_pdf_report.py <run_output_dir> <app_root>", file=sys.stderr)
        sys.exit(1)

    run_dir  = Path(sys.argv[1])
    app_root = Path(sys.argv[2])
    pdf_path_override = Path(sys.argv[3]) if len(sys.argv) > 3 and sys.argv[3] else None
    prepared_by_arg   = sys.argv[4] if len(sys.argv) > 4 else ""
    logo     = app_root / "assets" / "logo.png"

    manifest        = load_json(run_dir / "manifest.json")        or {}
    findings_data   = load_json(run_dir / "findings.json")        or {}
    remediation_data= load_json(run_dir / "remediation.json")     or {}

    client      = manifest.get("client",       "Unknown Client")
    location    = manifest.get("location",     "Unknown Location")
    note        = manifest.get("note",         "")
    date_stamp  = manifest.get("generated_at", "Unknown Date")
    prepared_by = prepared_by_arg or manifest.get("prepared_by",  "")

    pdf = Report(
        client      = client,
        location    = location,
        note        = note,
        date_stamp  = date_stamp,
        prepared_by = prepared_by,
        logo_path   = str(logo) if logo.exists() else None,
    )
    pdf.add_page()
    pdf.cover()

    # ── Executive Summary ──────────────────────────────────────────────────
    pdf.section_title("Executive Summary - Key Findings")
    findings = findings_data.get("findings") or []
    if not findings:
        pdf.note("No notable findings were generated from this scan set.")
    else:
        for i, f in enumerate(findings):
            pdf.finding_row(
                f.get("severity", "info"),
                f.get("title",    ""),
                f.get("detail",   ""),
                shade=i % 2 == 0,
            )

    # ── Remediation Hints ──────────────────────────────────────────────────
    hints = remediation_data.get("hints") or []
    if hints:
        pdf.section_title("Remediation Hints")
        for i, h in enumerate(hints):
            pdf.hint_row(h.get("title", ""), h.get("detail", ""), shade=i % 2 == 0)

    # ── Audit Results ──────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Audit Results - Per Task")

    def get(task_id):
        p = task_json_path(run_dir, manifest, task_id)
        return load_json(p) if p and p.exists() else None

    if d := get(1):  render_interface_info(pdf, d)
    if d := get(2):  render_speed_test(pdf, d)
    if d := get(3):  render_gateway(pdf, d)
    if d := get(4):  render_dhcp(pdf, d)
    if d := get(5):  render_generic_scan(pdf, 5,  "DNS Network Scan",              d)
    if d := get(6):  render_generic_scan(pdf, 6,  "LDAP/AD Network Scan",          d)
    if d := get(7):  render_generic_scan(pdf, 7,  "SMB/NFS Network Scan",          d)
    if d := get(8):  render_generic_scan(pdf, 8,  "Printer/Print Server Network Scan", d)
    if d := get(9):  render_stress_test(pdf, 9,   "Gateway Stress Test",           d)
    if d := get(10): render_vlan_trunk(pdf, d)

    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 11), 1):
        if d := load_json(p): render_custom_port_scan(pdf, d, i)
    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 12), 1):
        if d := load_json(p): render_custom_stress(pdf, d, i)
    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 13), 1):
        if d := load_json(p): render_custom_identity(pdf, d, i)
    for i, p in enumerate(all_task_json_paths(run_dir, manifest, 14), 1):
        if d := load_json(p): render_custom_dns_assessment(pdf, d, i)

    # ── Output path ────────────────────────────────────────────────────────
    if pdf_path_override:
        pdf_path = pdf_path_override
    else:
        report_txt = manifest.get("report_file", "")
        if report_txt:
            pdf_path = run_dir / (Path(report_txt).stem + ".pdf")
        else:
            def slug(s): return s.lower().replace(" ", "-")
            pdf_path = run_dir / f"lss-network-tools-report-{slug(client)}-{slug(location)}.pdf"

    pdf.output(str(pdf_path))
    print(str(pdf_path))


if __name__ == "__main__":
    main()
